version: '3'
services:
  nodejs-todo:
    image: ghcr.io/belkacemredouane/nodejs-todo:latest
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

